/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MouthwashRouteImport } from './routes/mouthwash'
import { Route as OralbrushRouteImport } from './routes/oralbrush'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MouthwashRoute = MouthwashRouteImport.update({
  id: '/mouthwash',
  path: '/mouthwash',
  getParentRoute: () => rootRouteImport,
} as any)
const OralbrushRoute = OralbrushRouteImport.update({
  id: '/oralbrush',
  path: '/oralbrush',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mouthwash': typeof MouthwashRoute
  '/oralbrush': typeof OralbrushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mouthwash': typeof MouthwashRoute
  '/oralbrush': typeof OralbrushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mouthwash': typeof MouthwashRoute
  '/oralbrush': typeof OralbrushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mouthwash' | '/oralbrush'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mouthwash' | '/oralbrush'
  id: '__root__' | '/' | '/mouthwash' | '/oralbrush'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MouthwashRoute: typeof MouthwashRoute
  OralbrushRoute: typeof OralbrushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mouthwash': {
      id: '/mouthwash'
      path: '/mouthwash'
      fullPath: '/mouthwash'
      preLoaderRoute: typeof MouthwashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oralbrush': {
      id: '/oralbrush'
      path: '/oralbrush'
      fullPath: '/oralbrush'
      preLoaderRoute: typeof OralbrushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MouthwashRoute: MouthwashRoute,
  OralbrushRoute: OralbrushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
